# Generated by Django 4.1.7 on 2023-04-10 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_adminweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adminId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.adminweb'),
        ),
        migrations.AlterField(
            model_name='adminweb',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminweb',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminweb',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
    ]
