# Generated by Django 4.1.7 on 2023-04-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_adminid_alter_adminweb_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('number', models.CharField(default='', max_length=50)),
                ('assingTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'verbose_name': 'StudentData',
                'verbose_name_plural': 'StudentDatas',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
