# Generated by Django 4.1.7 on 2023-04-10 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_studentdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adminId',
        ),
        migrations.AddField(
            model_name='user',
            name='aId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.adminweb'),
        ),
    ]
