# Generated by Django 4.1.7 on 2023-04-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_user_adminid_user_aid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aId',
        ),
    ]
