# Generated by Django 4.1.7 on 2023-04-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_user_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aId',
            field=models.CharField(default='', max_length=20),
        ),
    ]
