# Generated by Django 4.1.7 on 2023-04-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_aid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminWeb',
        ),
    ]
