# Generated by Django 4.1.7 on 2023-04-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_adminweb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='assingTo',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
