# Generated by Django 4.1.7 on 2023-04-10 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_adminweb_user_studentdata_assingto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adminweb'),
        ),
    ]
