# Generated by Django 4.1.7 on 2023-04-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_user_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='assingTo',
            field=models.BigIntegerField(),
        ),
    ]
