# Generated by Django 4.1.7 on 2023-04-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_studentdata_assingto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='assingTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
