# Generated by Django 4.1.7 on 2023-04-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
