# Generated by Django 4.1.7 on 2023-04-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_studentdata_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
