# Generated by Django 4.1.7 on 2023-04-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_studentdata_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='dateAt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
