# Generated by Django 4.1.7 on 2023-04-27 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_studentdata_dateat'),
    ]

    operations = [
        migrations.CreateModel(
            name='voiceRecData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.TextField(default='', max_length=200)),
                ('text', models.TextField(default='', max_length=3000)),
                ('feedback', models.IntegerField(default='')),
                ('voiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentdata')),
            ],
            options={
                'verbose_name': 'Voice Data',
                'verbose_name_plural': 'Voices Data',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
