# Generated by Django 4.1.7 on 2023-04-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_voicerecdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='callEn',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='callSt',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
