# Generated by Django 4.1.7 on 2023-05-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_studentdata_callen_studentdata_callst'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='stDetails',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='stFeedBack',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
